### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [sjricketts/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations

Great job taking this project on! Your code contains all the necessary elements and it's very easy to read due to your consistent formatting and alignment. You are getting a great handle on how to apply classes and ids, and when to choose which. Your CSS is well-done also!

Moving forward, start using div wrappers as a tool for grouping related elements. Also, always be on the lookout for ways to simplify your code and cut out unnecessary repetition. When it comes to readability, commenting is a great habit to develop now. Write little details about what each block of code does to make it easier for collaborators to read through your work. Finally, on the CSS side of things, there are a lot of resources for making the app more interesting visually. You can do that by using Google Fonts to find cool fonts, and Coolors.co to generate free color palettes to implement in your design. You might find those fun to play with. Again, great job and congratulations!

**Comment by sjricketts** [comment]
Thank you for the feedback! Great notes that I will definitely keep in mind as a move forward. Also, thanks for getting back to me so soon after I submitted my code-I appreciate it.
